version: '3'
services:
  web-front:
    platform: linux/amd64
    image: 'eorjs37/vue-typescript'
    restart: always
    container_name: 'web-front'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
