version: '3'
services:
  web-front:
    image: 'vue-typescript'
    container_name: 'web-front'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    expose:
      - "80"
