version: '3'
services:
  web-front:
    platform: linux/amd64
    image: 'eorjs37/vue-typescript'
    restart: always
    container_name: 'web-front'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "444:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/sectigo:/etc/sectigo
    networks:
      - default
      - jenkins-network
    environment:
      TZ: "Asia/Seoul"

networks:
  jenkins-network:
    driver: bridge
